# Generated by Django 3.1 on 2020-09-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('student_address', models.CharField(max_length=120)),
                ('course', models.CharField(choices=[('ACC', 'Accounting'), ('ICT', 'Information Communications Technology'), ('MEDTECH', 'Medical Technology'), ('CIVENG', 'Civil Engineer')], default=None, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'students',
                'ordering': ['last_name'],
            },
        ),
    ]
