# Generated by Django 3.1 on 2020-09-04 03:27

import django.core.validators
from django.db import migrations, models
import teachers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_number', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[(teachers.models.Type['MALE'], 'M'), (teachers.models.Type['FEMALE'], 'F'), (teachers.models.Type['UNDEFINED'], 'U')], max_length=10)),
                ('address', models.CharField(max_length=120)),
                ('mobile_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number', regex='^\\+1?d{9,15}')])),
            ],
            options={
                'verbose_name_plural': 'teachers',
                'ordering': ['last_name'],
            },
        ),
    ]
