# Generated by Django 3.1 on 2020-09-04 04:14

from django.db import migrations, models
import teachers.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', teachers.models.Type['MALE']), ('F', teachers.models.Type['FEMALE']), ('U', teachers.models.Type['UNDEFINED'])], max_length=10),
        ),
    ]
