# Generated by Django 3.1 on 2020-09-04 04:18

from django.db import migrations, models
import teachers.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200903_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[(teachers.models.Type['MALE'], 'MALE'), (teachers.models.Type['FEMALE'], 'FEMALE'), (teachers.models.Type['UNDEFINED'], 'UNDEFINED')], max_length=10),
        ),
    ]
