# Generated by Django 3.1 on 2020-09-04 04:25

from django.db import migrations, models
import phonenumber_field.modelfields
import teachers.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20200903_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('MALE', teachers.models.Type['MALE']), ('FEMALE', teachers.models.Type['FEMALE']), ('UNDEFINED', teachers.models.Type['UNDEFINED'])], max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
